defaults:
    - _self_

model:
    block_count: 5
    hidden_size: 1000
    save_name: "./models/model.safetensors"
    pull_dvc: True

optim:
    optim_type: "Adam"

trainer:
    epochs: 3
    batch_size: 4096

dataset:
    train_size: 463715
